version: "3"

networks:
  grafana:

services:

  influxdb:
    image: influxdb:2.6
    ports:
     - 8086:8086
     - 8083:8083
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=super-secret-admin-password-12345
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    networks:
      - grafana

  grafana:
    image: grafana/grafana:8.4.5
    volumes:
      - ./provisioning/:/etc/grafana/provisioning/
      - ./src:/var/lib/grafana/dashboards
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
      - "GF_INSTALL_PLUGINS=natel-plotly-panel"